CREATE TABLE TBL_POST (
    id_post INT IDENTITY(1,1) PRIMARY KEY,
    id_user INT NOT NULL,
    txt_nome VARCHAR(50) NOT NULL,
    txt_description VARCHAR(255) NOT NULL,
    CONSTRAINT FK_TBL_POST_User FOREIGN KEY (id_user) REFERENCES TBL_USER(id_user) ON DELETE CASCADE
);